CREATE TYPE stateType AS ENUM(
    'asleep', 'awake'
    );
CREATE TYPE CONTROLType AS ENUM(
    'manual', 'automatic'
    );
CREATE TYPE GENDER AS ENUM(
    'male', 'female'
    );
CREATE TABLE IF NOT EXISTS spaceship(
    ID SERIAL PRIMARY KEY,
    cLocation VARCHAR(30) NOT NULL,
    integrity VARCHAR(20) NOT NULL,
    situation VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS crewMember(
    ID SERIAL PRIMARY KEY,
    fullName TEXT NOT NULL,
    age SMALLINT NOT NULL,
    gender GENDER NOT NULL
);
CREATE TABLE IF NOT EXISTS HAL9000(
    ID SERIAL PRIMARY KEY,
    state BOOL DEFAULT(TRUE) NOT NULL,
    FOREIGN KEY(ID) REFERENCES spaceship(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS sarcophagus(
    ID SERIAL PRIMARY KEY,
    state stateType NOT NULL,
    FOREIGN KEY(ID) REFERENCES crewMember(ID)
);
CREATE TABLE IF NOT EXISTS crew(
    ID SERIAL PRIMARY KEY,
    spaceshipID INT NOT NULL,
    teamwork TEXT NOT NULL,
    FOREIGN KEY(spaceshipID) REFERENCES spaceship(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS control(
    ID SERIAL PRIMARY KEY,
    CONTROL CONTROLType NOT NULL,
    FOREIGN KEY(ID) REFERENCES HAL9000(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS RANK(
    ID SERIAL PRIMARY KEY,
    RANK VARCHAR(15) NOT NULL,
    FOREIGN KEY(ID) REFERENCES crewMember(ID) ON DELETE CASCADE
);
