listen_addresses = '*'
wal_level = hot_standby
hot_standby = on
primary_conninfo = 'host=primary port=5432 user=replicator password=replicator_password'
max_wal_senders = 10
archive_mode = on
archive_command = 'echo "dummy command, archive_command called"'

